# Generated by Django 4.2 on 2026-01-16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DiagnosisResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("client_started_at", models.DateTimeField(blank=True, null=True)),
                ("client_submitted_at", models.DateTimeField(blank=True, null=True)),
                ("lang", models.CharField(default="ENG", max_length=8)),
                ("user_agent", models.TextField(blank=True, default="")),
                ("answers", models.JSONField(default=list)),
                ("birth_year", models.IntegerField(blank=True, null=True)),
                ("result_code", models.IntegerField(blank=True, null=True)),
                ("skin_age", models.IntegerField(blank=True, null=True)),
                ("skin_percentile", models.IntegerField(blank=True, null=True)),
                ("score_a", models.IntegerField(blank=True, null=True)),
                ("score_b", models.IntegerField(blank=True, null=True)),
                ("total_score", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["created_at"], name="diag_created_at_idx"),
                    models.Index(fields=["result_code"], name="diag_result_code_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ButtonClick",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("button_key", models.CharField(max_length=32)),
                ("lang", models.CharField(default="ENG", max_length=8)),
                (
                    "diagnosis",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clicks",
                        to="diagnosis.diagnosisresult",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["created_at"], name="click_created_at_idx"),
                    models.Index(fields=["button_key"], name="click_button_key_idx"),
                ],
            },
        ),
    ]
